export default {
    KERALA:{
        THIRUVANANTHAPURAM:[
            'Adayamon',	
            'Alamcode',	
            'Aliyadu',	
            'Altharamoodu',	
            'Amachal',	
            'Amaravila',	
            'Ambalamukku',	
            'Ambalathara',	
            'Ambalathinkala',	
            'Amboori',	
            'Anad',
            'Anakudy',	
            'Anappara'	,
            'Anathalavattom',	
            'Anavoor',	
            'Anayara'	,
            'Andoorkonam'	,
            'Anjengo'	,
            'Aralumoodu',
            'Aramada'	,
            'Arayur'	,
            'Arumanoor'	,
            'Aruvikara'	,
            'Aruvipuram'	,
            'Aryanad',	
            'Attakulangara',
            'Attingal',	
            'Attukkal'	,
            'Avanavancherry'	,
            'Ayilam',
            'Ayira',
            'Ayroor-varkala	',
            'Azhurmarket',	
            'Balaramapuram'	,
            'Beemapally',
            'Bhagavathinada',	
            'Bharathannur',	
            'Bonaccord'	,
           ' Cgo Complex Poonkulam',
            'Chaikkottukonam',	
            'Chakkai'	,
            'Changa'	,
            'Channamkara',
            'Charupara'	,
            'Cheeranikkara'	,
            'Chekkakonam',
            'Chempazhanthy',
            'Chenkal'	,
            'Cheriakolla',
            'Cheriyakonni'	,
            'Cherunniyur',
            'Cheruvallimukku',	
            'Cheruvarakonam',	
            'Cheruvikkal',	
            'Chettachal',	
            'Chilakur',	
            'Chirayinkeezhu',	
            'Chittattumukku',	
            'Chowara',	
            'Chullimanoor',	
           ' Cotton Hill	',
            'Daivapura'	,
            'Dalmughom',	
            'Dhanuvachapuram',	
            'Edakode',	
            'Edava'	,
            'Elakamon',	
            'Elakamon-kizhakkepuram	',
            'Elavattom',	
            'Elluvila',	
            'Ex-servicemen Colony	',
            'Goureesapattom',	
            'Hariharapuram'	,
            'Idinjar',	
            'Ilamba',	
            'Ilanchiyam',	
            'Industrial Estate	',
            'Irinchayam',	
            'Iroopara',	
            'Jagathy',	
            'Janardhanapuram',	
            'Kadakkavur',
            'Kaikara',	
            'Kaimanam',
            'Kaithamukku',	
            'Kakkavila',	
            'Kalamachal',	
            'Kallambalam',	
            'Kallar Tvm	',
            'Kallara',	
            'Kallayam'	,
            'Kalliyal',	
            'Kalliyoor'	,
            'Kanchinada',	
            'Kandala',	
            'Kandukrishi',	
            'Kaniyapuram',	
            'Kanjampazhanji',	
            'Kanjiramkulam'	,
            'Kanjirampara',	
            'Kappil',	
            'Karakonam',
            'Karakulam'	,
            'Karamana',	
            'Karavaram'	,
            'Karikkakom',	
            'Karikuzhi'	,
            'Karimanal'	,
            'Karimancode',	
            'Karimkuttikara',	
            'Karipur',	
            'Karode',	
            'Karumom',	
            'Karyavattom',	
            'Katakam'	,
            'Kattachalkuzhy',	
            'Kattacode'	,
            'Kattaikonam',
            'Kattakada'	,
            'Kattumpuram',	
            'Kaudiar',	
            'Kaudiar Square	',
            'Kavalayur',	
            'Kazhakuttam',	
            'Kazhavur'	,
            'Keezharur'	,
            'Keezhattingal'	,
            'Keezhavur'	,
            'Kerala Governors Camp',
            'Kidarakuzhy',	
            'Kilimanur Palace	',
            'Kilmanur',	
            'Kizhuvalam',	
            'Kochuvila'	,
            'Kodithookiyakunnu',	
            'Kodunganur',	
            'Kodungavila',	
            'Koduvazhannur',	
            'Koithurkonam',	
            'Kokkotela'	,
            'Kokkottukonam'	,
            'Koliakode'	,
            'Kollode',	
            'Konchira',	
            'Koonanvenga'	,
            'Koothali(TVM)'	,
            'Kottackal (TVM)	',
            'Kottakkakom',	
            'Kottapuram',	
            'Kottoor(TVM)'	,
            'Kottukal',	
            'Kottukunnam',
            'Kovalam Beach'	,
            'Kovalam',	
            'Kudappanakunnu',	
            'Kudappanamoodu',
            'Kudavur',	
            'Kudayal',	
            'Kulamuttam',	
            'Kulappada'	,
            'Kulathur',	
            'Kunnathukal',	
            'Kurakkada'	,
            'Kurumbayam',
            'Kuruthamcode'	,
            'Kuthirakalam-vellanad	',
            'Kuthirakulam',	
            'Kuttamala',	
            'Kuttichal'	,
            'Kuvalassery',	
            'Lourdepuram',	
            'Machel',	
            'Madavoor-pallickal',
            'Malakkal'	,
            'Malayam',	
            'Malayinkil',	
            'Manacaud',	
            'Manali',	
            'Manambur',	
            'Mancha',	
            'Manchamcode',	
            'Manchavilakom',	
            'Manikanteswaram',	
            'Manjamala'	,	
            'Mannamkonam',	
            'Mannanathala',	
            'Mannurkonam',	
            'Marangad'	,
            'Marayamuttom'	,
            'Mariyapuram',	
            'Maruthamala',	
            'Maruthikunnu'	,
            'Mayam',
            'Meenankal'	,
            'Meenmutty'	,
            'Melkadakkavur'	,
            'Melvettoor',
            'Memala',	
            'Mg College',
            'Mithirmala',	
            'Mithraniketan'	,
            'Moongode',
            'Moonnanakuzhy'	,
            'Moonnumukku',	
            'Moothala',	
            'Mudakkal',	
            'Mudapuram'	,
            'Mukkolackal',	
            'Mukkudil',	
            'Mulakkalathukavu',
            'Mulayara',	
            'Mullur',	
            'Mulluvila'	,
            'Mundela'	,
            'Murukumpuzhaa',	
            'Muthana',	
            'Muthuvila',	
            'Muttada',	
            'Muttakadu'	,
            'Muttappalam',
            'Mylakkara',	
            'Mylamoodu',	
            'Nagaroor',	
            'Nalanchira',	
            'Naruvamoodu',	
            'Navaikulam',
            'Nedumangad',	
            'Nedumparambu',	
            'Nedunganda',	
            'Neeramankadavuu',	
            'Nellanad',	
            'Nellimoodu',	
            'Nellivila',	
            'Nemom',
            'Nethajipuram'	,
            'Nettayam',	
            'Neyyar Dam',
            'Neyyattinkara'	,
            'Neyyattinkara Town	',
            'Nilakkamukku',	
            'Njarayilkonam',	
            'Odayam',	
            'Olathanni',	
            'Ookode',	
            'Oorupoika',	
            'Ooruttambalam'	,
            'Ottasekharamangalam',	
            'Pacha',
            'Pachallur',	
            'Pakalkuri'	,
            'Palachira',	
            'Palamkonam',	
            'Palayamkunnu',	
            'Palkulangara',	
            'Pallichal',
            'Pallickal Kilimanur	',
            'Pallipuram',	
            'Pallithura',	
            'Paluvally',	
            'Panachamoodu',	
            'Panacode',	
            'Panangode'	,
            'Panavoor',	
            'Panayam',	
            'Panayamuttom',	
            'Panayara',
            'Pandalacode',	
            'Pangappara',	
            'Pangode',	
            'Panniyode',	
            'Pantha',	
            'Pappanamcode',	
            'Parakunnu',	
            'Parandode',	
            'Parappara'	,
            'Parassala',	
            'Parasuvaickal',
            'Parayathukonam',	
            'Paruthikuzhy',	
            'Paruthipally',	
            'Pattom Palace',	
            'Payattuvila',	
            'Pazhakutty',	
            'Pazhayakunnummel',
            'Peppara Dam',
            'Perayam',	
            'Peringamala',	
            'Peroor',	
            'Perukavu',	
            'Perumathura',	
            'Perumkadavila',	
            'Perumkulam',	
            'Perumpazhuthoor',	
            'Perunguzhi',
            'Perurkada',	
            'Peyad',
            'Pirappancode',	
            'Plamootukada',	
            'PMG Jn',	
            'Poikamukku',	
            'Ponganadu',	
            'Ponmudi',	
            'Poojapura',	
            'Poojapura Junction',	
            'Poonthura',	
            'Poothura',	
            'Poovachal',	
            'Poovathur',	
            'Poozhanad',	
            'Pothencode',	
            'Powdikonam',	
            'Pozhiyoor',	
            'Prasanth Nagar	',
            'Pravachambalam',	
            'PTP Nagar',	
            'Public Office	',
            'Pulimath',	
            'Puliyarakonam',	
            'Puliyurkonam',	
            'Pullampara',	
            'Pullanicode',	
            'Pullayil',	
            'Pulluvila',	
            'Punalal',	
            'Puthencurichy',	
            'Puthenthope',
            'Puthiathura',	
            'Puthukulangara',	
            'Puthusserimukku',	
            'Puvar',	
            'Russelpuram',	
            'Sainik School	',
            'Santhigiri',	
            'Sasthamangalam',	
            'Sasthavattom',	
            'Sreekaryam',	
            'Sreenivasapuram',	
            'St.Xavier College	',
            'Thalikuzhi',	
            'Thamalam',	
            'Thannimoodu',	
            'Thattathumala',	
            'Thekkupara',	
            'Thennur',	
            'Thiruvallom',
            'Thiruvananthapuram',	
            'Chalai',
             'Fort',	
            'Medical College',
           'Pettah',	
            'Thiruvananthapuram University	',
            'Thokkad',	
            'Tholicode',	
            'Thonnakkal',	
            'Thope',
            'Thottakkad',
            'Thundathil',	
            'Thuruvikkal',	
            'Thycaud',	
            'Tirumala',	
            'Tirupuram'	,
            'Titanium',	
            'TVM R.K Mission	',
            'Uchakada',	
            'Ulloor',	
            'Uriakode',	
            'Vadasserikonam',	
            'Vakkom',	
            'Valiamala',	
            'Valiathura',	
            'Valiaveli',	
            'Valiavila',	
            'Vallakkadavoo',	
            'Vamanapuram',	
            'Vanchiyoor Junction	',
            'Vanchiyur',
            'Vanchiyur-attingal	',
            'Varkala',	
            'Varkala South'	,
            'Vattakarikkakom',	
            'Vattappara',	
            'Vattavila'	,
            'Vattiyoorkavu'	,
            'Vazhichal',	
            'Vedivachankoil',	
            'Veeranakavu',	
            'Veliyamcode',	
            'Veliyannur',	
            'Vellallur',	
            'Vellanad',	
            'Vellarada',	
            'Vellayani'	,
            'Vellumannady'	,
            'Vembayam'	,
            'Venganur',	
            'Venjaramoodu',	
            'Venkadambu',
            'Venkode',	
            'Venkulam',
            'Vennicode',	
            'Venpakal'	,
            'Vettiyara'	,
            'Vikas Bhavan',	
            'Vilappilsala',	
            'Vinobaniketan'	,
            'Vithura',	
            'Vizhinjam',
            'Vlathankara'	
        ]
    }
}