export default {
    MOBILE_BRANDS:[
        'Select',
        'Apple',
        'BlackBerry',
        'Celkon',
        'CoolPad',
        'Gionee',
        'Google',
        'Honor',
        'Huawei',
        'Infinix',
        'intex',
        'IQOO',
        'Itel',
        'Lava',
        'Lenovo',
        'LG',
        'Micromax',
        'Moto',
        'Nokia',
        'NOTHING',
        'OnePlus',
        'Oppo',
        'Panasonic',
        'Poco',
        'Realme',
        'Redmi',
        'Samsung',
        'Sony',
        'Vivo',
        'Other' 
    ],
    MOBILE_MODELS:{
        Apple:[
            'iPhone 14 Pro Max',
            'iPhone 14 Pro',
            'iPhone 14 Plus',
            'iPhone 14',
            'iPhone SE(2022)',
            'iPhone 13 Pro Max',
            'iPhone 13 Pro',
            'iPhone 13',
            'iPhone 13 mini',
            'iPhone 12 Pro Max',
            'iPhone 12 Pro',
            'iPhone 12',
            'iPhone 12 mini',
            'iPhone SE(2020)',
            'iPhone 11 Pro Max',
            'iPhone 11 Pro',
            'iPhone 11',
            'iPhone XS Max',
            'iPhone XS',
            'iPhone XR',
            'iPhone X',
            'iPhone 8 Plus',
            'iPhone 8',
            'iPhone 7 Plus',
            'iPhone 7',
            'iPhone SE(2016)',
            'iPhone 6s Plus',
            'iPhone 6s',
            'iPhone 6 Plus',
            'iPhone 6',
            'iPhone 5s',
            'iPhone 5c',
            'iPhone 5',
            'iPhone 4s',
            'iPhone ',
            'Other'

        ],
        BlackBerry:[
            'Evolve X',
            'Evolve',
            'Motion',
            'Aurora',
            'DTEK60',
            'DTEK50',
            'Leap',
            'Z3',
            'Porsche Design',
            'Z30',
            'Other'

        ],
        Celkon:[
            'Millennia Everest',
            "Millennia Hero",
            'Millennia Xplore',
            'Q5K Power',
            'Millennia Octa510',
            'Millennia Epic Q550',
            'Q500 Millennium Ultra',
            'Other'
        ],
        CoolPad:[
            'Cool 20s',
            'Cool 20',
            'Cool 20 Pro',
            'Cool 10A',
            'Cool S',
            'Cool 6',
            'Cool 12A',
            'Cool 10',
            'Cool 5',
            'Cool 3 Plus',
            'Cool Play 8',
            'Cool 2',
            'Cool Play 6',
            'Cool M7',
            'Cool1 dual',
            'Cool S1',
            'Legacy 5G',
            'Legacy',
            'Max',
            'Note 6',
            'Note 5 Lite',
            'Note 3s',
            'Note 3 Plus',
            'Note 5',
            'Note 3 Lite',
            'Note 3',
            'Porto',
            'Other'

        ],
        Gionee:[
            'G13 Pro',
            'P15',
            'M15',
            'M3',
            'P15 Pro',
            'Max Pro',
            'K30 Pro',
            'P12',
            'M12',
            'S12 Lite',
            'S12',
            'M30',
            'Max',
            'K3 Pro',
            'K6',
            'F205',
            'S11S',
            'S11',
            'S11 Lite',
            'M7 plus',
            'M7 Power',
            'M7',
            'X1s',
            'X1',
            'P8 Max',
            'A1 Lite',
            'S10',
            'M6s Plus',
            'A1 Plus',
            'A1',
            'F5',
            'Steel 2',
            'S9',
            'P7',
            'P7 Max',
            'Other'
        ],
        Google:[
            'Pixel 6a',
            'Pixel 6 Pro',
            'Pixel 6',
            'Pixel 5a 5G',
            'Pixel 5',
            'Pixel 4a 5G',
            'Pixel 4a',
            'Pixel 4 XL',
            'Pixel 4',
            'Pixel 3a XL',
            'Pixel 3a',
            'Pixel 3 XL',
            'Pixel 3',
            'Pixel 2',
            'Pixel 2 XL',
            'Pixel XL',
            'Pixel',
            'Other'
        ],
        Honor:[
            'X40',
            'X8 5G',
            'X40i',
            '70 Pro Plus',
            '70 Pro',
            '70',
            'Play 30',
            'Play 6T Pro',
            'Play 6T',
            'Magic 4 Lite',
            'X7',
            'X9',
            'X9 5G',
            'Magic 4 Ultimate',
            'X8',
            'Magic 4 Pro',
            'Magic 4',
            '60 SE',
            'Magic V',
            'X30',
            'Play 30 Plus',
            '60 Pro',
            '60',
            'X30 Max',
            'X30i',
            '50 Lite',
            'Play5 Youth',
            'X20',
            'Magic 3 Pro Plus',
            'Magic 3 Pro',
            'Magic 3',
            'Play 5T Pro',
            'X20 SE',
            '50 Pro',
            '50',
            '50 SE',
            'Play5 5G',
            'Play 20',
            'Play 5T Youth',
            'V40 Lite',
            'View 40',
            'V40 5G',
            'Other'
        ],
        Huawei:[
            'Mate 50 RS',
            'Mate 50 Pro',
            'Mate 50E',
            'Mate 50',
            'nova 10z',
            'nova 10 Pro',
            'nova 10',
            'nova Y90',
            'nova 9 SE 5G',
            'nova Y70 Plus',
            'P50E',
            'nova 9 SE',
            'nova 8 SE 4G',
            'nova Y60',
            'nova 9 Pro',
            'nova 9',
            'nova 8',
            'P50 Pro',
            'P50',
            'nova 8 SE Youth',
            'nova 8i',
            'Mate 40 Pro',
            'Mate 40E 4G',
            'Mate X2 4G',
            'nova 8 Pro',
            'Mate 40E',
            'P40 4G',
            'Mate X2',
            'nova 8 Pro 5G',
            'nova 8 5G',
            'nova 8 SE',
            'Mate 40 RS',
            'Mate 40 Pro Plus',
            'Mate 40 Pro',
            'Mate 40',
            'Mate 30E Pro 5G',
            'nova 7 SE 5G Youth',
            'Y7a',
            'Y9a',
            'P Smart S',
            'Y8p',
            'P40 lite 5G',
            'Y8s',
            'Y6p',
            'Other'
        ],
        Infinix:[
            'Zero 20',
            'Note 12',
            'Note 12 Pro',
            'Note 12 Pro 5G',
            'Note 12 5G',
            'Smart 6 Plus',
            'Hot 12 Pro',
            'Hot 11s',
            'Note 12i',
            'Hot 12',
            'Smart 6 HD',
            'Smart 5 Pro',
            'Note 11i',
            'Note 11s',
            'Note 11',
            'Smart 6',
            'Other'
        ],
        intex:[
            'Aqua Craze',
            'Aqua GenX',
            'Aqua Ace',
            'Aqua Trend',
            'Aqua 4G Plus',
            'Aqua Xtreme II',
            'Aqua Star 2',
            'Other'
        ],
        IQOO:[
            'Z6 Lite 5G',
            'Neo 6 5G',
            'Z6 5G',
            'Neo 7 5G',
            'Z5 5G',
            'Z6 Pro 5G',
            'Z6 Lite',
            '9 SE 5G',
            'Z6 5G',
            'Z6 4G',
            'Neo 6 SE 5G',
            '9T 5G',
            '9 5G',
            '10 Pro 5G',
            '7',
            'Other'
        ],
        Itel:[
            'Vision 3',
            'A49',
            'A26',
            'Vision 2S',
            'A48',
            'Vision 2',
            'A47',
            'Vision 1',
            'A46',
            'A44 Air',
            'A22 Pro',
            'A22',
            'A45',
            'A44 Pro',
            'A44',
            'S42',
            'S41',
            'Power Pro P41',
            'Vision 3 Turbo',
            'Other'
        ],
        Lava:[
            'Blaze 5G',
            'Blaze Pro',
            'Blaze',
            'Z3',
            'X2',
            'Agni 5G',
            'Z2s',
            'Z2 Max',
            'Z6',
            'Z4',
            'Z2',
            'Z1',
            'Z61 Pro',
            'Z71',
            'Z40',
            'Z92',
            'Z81',
            'Z60s',
            'Z61',
            'Z91',
            'A77',
            'Z25',
            'Z10',
            'X41 Plus',
            'Other'
        ],
        Lenovo:[
            'Legion Y70',
            'Legion Y90',
            'K13 Pro',
            'K13',
            'K13 Note',
            'Legion 2 Pro',
            'Legion Duel 2',
            'K12 Pro',
            'A8 2020',
            'Legion Duel',
            'Legion Pro',
            'A7',
            'K10 Plus',
            'K10 Note',
            'A6 Note',
            'Z6',
            'Z6 Pro 5G',
            'Z6 Youth',
            'Z6 Pro',
            'K6 Enjoy',
            'S5 Pro GT',
            'Z5s',
            'Z5 Pro GT',
            'Z5 Pro',
            'S5 Pro',
            'K5 Pro',
            'K9',
            'Z5',
            'K5 Note(2018)',
            'A5',
            'K5',
            'S5',
            'K320t',
            'K8 Plus',
            'K8',
            'K8 Note',
            'A6600 Plus',
            'A6600',
            'B',
            'A Plus',
            'P2',
            'K6 Note',
            'K6 Power',
            'k6',
            'Phab2 Plus',
            'Phab2',
            'Phab2 Pro',
            'Vibe C',
            'Vibe K5 Plus',
            'Vibe K5',
            'A7000 Turbo',
            'Vibe P1 Turbo',
            'K5 Note',
            'Vibe K4 Note',
            'Vibe X3',
            'Vibe P1',
            'Other'
        ],
        LG:[
            'W41 Pro',
            'W41 Plus',
            'W41',
            'W31 Plus',
            'W321',
            'W11',
            'K62',
            'Q52',
            'K52',
            'K92 5G',
            'K42',
            'K71',
            'K22',
            'Q31',
            'K31',
            'Q61',
            'Stylo 6',
            'Velvet',
            'Velvet 5G',
            'V60 ThinQ 5G UW',
            'V60 ThinQ 5G',
            'Q51',
            'K61',
            'K30',
            'K20',
            'W30 Pro',
            'W30',
            'W10',
            'Q60',
            'K50',
            'K40',
            'Q9',
            'V40 ThinQ',
            'Candy',
            'G7 One',
            'K11 Plus',
            'Other'
        ],
        Micromax:[
            'In 2c',
            'In note 2',
            'In 2b',
            'In 1',
            'In note 1',
            'In 1b',
            'Infinity N12',
            'Infinity N11',
            'Bharat 5 Infinity',
            'Bharat Go',
            'Canvas Infinity Pro',
            'Bharat 2 Ultra',
            'Canvas Selfie 3',
            'Bharat 4',
            'Bharat 3',
            'Selfie 2 Note',
            'Canvas Infinity',
            'Selfie 2',
            'Canvas 1',
            'Canvas 2',
            'Dual 5',
            'Canvas Fire 6',
            'Other'
        ],
        Moto:[
            'G72',
            'E22i',
            'E22',
            'Edge 30 Ultra',
            'Edge 30 Fusion',
            'Edge 30 Neo',
            'E22s',
            'Edge (2022)',
            'X30 Pro',
            'S30 Pro',
            'G62',
            'G32',
            'G62 5G',
            'G42',
            'E32s',
            'G71s',
            'G82',
            'E32',
            'Edge 30',
            'G Stylus 5G',
            'G (2022)',
            'G52',
            'G22',
            'Edge 30 Pro',
            'Edge X30',
            'Edge S30',
            'G200 5G',
            'G71 5G',
            'G51 5G',
            'G41',
            'G31',
            'G POwer (2022)',
            'E30',
            'G60',
            'E40',
            'E20',
            'G60s',
            'Edge 20 Pro',
            'Other'
        ],
        Nokia:[
            'X30',
            'G60',
            'C31',
            'G400',
            'T10',
            'G11 Plus',
            'C200',
            'C100',
            'C21 Plus',
            'C21',
            'C2 2nd  Edition',
            'G11',
            'G21',
            'X100',
            'G300',
            'T20',
            'G50',
            'XR20',
            'C30',
            'C1 2nd Edition',
            'C20 Plus',
            'C01 Plus',
            'X20',
            'X10',
            'G20',
            'G10',
            'C20',
            'C10',
            '1.4',
            '5.4',
            'C1 Plus',
            '8 V 5G UW',
            '2 V Tella',
            '2.4',
            'C3',
            'C5 Endi',
            '8.3 5G',
            '2.3',
            '7.2',
            '6.2',
            '3.1C',
            '3.1A',
            '2.2',
            'X71',
            '4.2',
            '3 V',
            '3.2',
            '1 Plus',
            'Other'
        ],
        NOTHING:[
            'Phone(1)'
        ],
        OnePlus:[
            'Ace Pro',
            'Nord N20 SE',
            '10T',
            'Nord 2T',
            'Ace Racing',
            'Nord N20 5G',
            '10R 150W',
            '10R',
            'Nord CE 2 Lite 5G',
            'Ace',
            '10 Pro',
            'Nord CE 2 5G',
            '9RT 5G',
            'Nord 2 5G',
            'Nord N200 5G',
            'Nord CE 5G',
            '9 Pro',
            '9',
            '9R',
            'Nord N10 5G',
            'Nord N100',
            '8T',
            '8T+ 5G',
            '8 Pro',
            '8',
            '7T Pro',
            '7T',
            '7 Pro',
            '7',
            '6T McLaren',
            '6T',
            '6',
            '5T',
            '5',
            '3T',
            '3',
            'X',
            '2',
            'One',
            '9E',
            'Other'
        ],
        Oppo:[
            'A17',
            'A57e',
            'A57s',
            'Reno 8 4G',
            'Reno 8 Z',
            'A77',
            'Reno 8 Pro',
            'Reno 8',
            'A97',
            'Reno 8 Lite',
            'K10x',
            'K10',
            'A77',
            'A57',
            'Reno 8 Pro Plus',
            'K10 Pro',
            'A55s',
            'Reno 7 Lite',
            'F21 Pro',
            'F21 Pro',
            'Reno 7',
            'A96',
            'A16e',
            'Reno 7 Z',
            'Find X5 Pro',
            'Find X',
            'Find X5 Lite',
            'A76',
            'Reno 6 Lite',
            'A36',
            'A11s',
            'A95',
            'A16K',
            'A54s',
            'A56',
            'K9s',
            'A55',
            'F19s',
            'K9 Pro',
            'Reno 6 Pro',
            'Reno 6',
            'Reno 6 Z',
            'Reno 6 Pro Plus',
            'A16s',
            'A16',
            'K9',
            'A53s',
            'A95',
            'A94',
            'A35',
            'Reno 5 Z',
            'A54',
            'A74',
            'F19',
            'F19 Pro Plus',
            'F19 Pro',
            'A93s',
            'A15s',
            'A73',
            'A15',
            'A33',
            'F17 Pro',
            'F17',
            'A12s',
            'A92',
            'A92s',
            'A72',
            'A11K',
            'A12',
            'A31',
            'F15',
            'A91',
            'A8',
            'A11',
            'K5',
            'A5',
            'A9',
            'Reno 2 Z',
            'A9x',
            'A9',
            'A1K',
            'F11',
            'F11 Pro',
            'A7',
            'R17',
            'F9 Pro',
            'F9',
            'A3s',
            'A3',
            'F7',
            'R15 Pro',
            'R15',
            'A71',
            'A83',
            'F5',
            'F3',
            'A39',
            'F3 Plus',
            'A57',
            'F1s',
            'A37',
            'A59',
            'F1 Plus',
            'F1',
            'Other'
        ],
        Panasonic:[
            'P90',
            'P95',
            'Eluga Z1 Pro',
            'Eluga Ray 800',
            'Eluga X1 Pro',
            'Eluga Ray 550',
            'P101',
            'Eluga A3 Pro',
            'Eluga A3',
            'P55 Max',
            'P85',
            'P88',
            'P77',
            'Eluga A2',
            'P66',
            'Other'
        ],
        Poco:[
            'M5s',
            'M5',
            'M4',
            'F4',
            'X4 GT',
            'C40',
            'F4 GT',
            'X4 Pro',
            'M4 Pro',
            'C31',
            'X3 GT',
            'F3 GT',
            'M3 Pro',
            'M2',
            'X3 Pro',
            'F3',
            'M3',
            'C3',
            'X3',
            'M2 Pro',
            'F2 Pro',
            'X2',
            'F1',
            'Other'
        ],
        Realme:[
            'C30s',
            'C33',
            '9i',
            'Narzo 50i Prime',
            'C30',
            'GT Neo 3T',
            'Narzo 50 Pro',
            'Narzo 50',
            '9',
            'Q5 Pro',
            'Q5',
            'Q5i',
            'C31',
            'GT Neo 3',
            'Narzo 50A Prime',
            '9 Pro+',
            '9 Pro',
            'C35',
            '9i',
            'GT2 Pro',
            'GT2',
            'Q3s',
            'C25Y',
            '8s',
            '8i',
            'C21Y',
            'C11',
            'C25s',
            'X7 Max',
            'Narzo 30',
            'Q3 Pro carnival',
            'C20A',
            'Q3 pro',
            'Q3',
            'Q3i',
            '8',
            'C25',
            'C21',
            'X7',
            'Q2 Pro',
            'Q2',
            'Q2i',
            'Narzo 20 Pro',
            'Narzo 20',
            'Narzo 20A',
            'C17',
            '7i',
            '7 Pro',
            '7',
            'X7 Pro',
            'X7',
            'C12',
            'C15',
            'C11',
            'X3',
            'Narzo',
            '6S',
            'X50 Pro Player',
            '6i',
            '6 Pro',
            '6',
            'Narzo 10',
            'Narzo 10A',
            '6i',
            'C3',
            '5i',
            'X2 Pro',
            'X2',
            'XT',
            '5 Pro',
            '5',
            '3i',
            'X',
            '3 Pro',
            'C2',
            '3',
            'C1',
            '2',
            '1',
            'X9 Pro',
            'X9'
        ],
        Redmi:[
            '12T Pro',
            '12T',
            'Note 11R',
            'A1+',
            '11 Prime',
            'A1',
            'Note 11',
            'K50 Ultra',
            'K50i',
            '12 Lite',
            '12S Ultra',
            '12S Pro',
            '12S',
            '12 Pro',
            'Note 11T Pro+',
            'Note 11T Pro',
            'Note 11SE',
            '10 Prime',
            '10 Power',
            '10A',
            'Note 11S',
            '10',
            'Note 11 Pro+',
            'K50 Pro',
            'K50',
            'K40S',
            '12 Pro',
            '12',
            '12X',
            '10',
            '10C',
            'Note 11E pro',
            'Note 11E',
            'K50 Gaming',
            'Note 11 Pro',
            'Note 11S',
            'Note 11T',
            'Note 10 Lite',
            '9i Sport',
            '9A Sport',
            '11T Pro',
            '11T Lite',
            '10 Prime',
            '10',
            'Note 10T',
            'Note 10 Pro',
            'Note 9 Pro',
            'Note 8 Pro',
            '11X Pro',
            '11X',
            '11 Ultra',
            '11 Pro',
            '11i',
            '11 Lite',
            '10S',
            'Note 10 Pro',
            'Note 10 Pro Max',
            'Note 10',
            'Note 10S',
            'Note 9T',
            '9T',
            '10i',
            '11',
            '9 Power',
            'Note 9',
            '10T Pro',
            '10T',
            '10T Lite',
            '9AT',
            '9i',
            '9',
            '9 Prime',
            '9A',
            '9C',
            '10X Pro',
            '10X',
            'Note 9 Pro Max',
            '8A Pro',
            '8A',
            '8T',
            '8',
            '8A',
            '9 Pro',
            '9 Lite',
            'A3',
            'Note 8',
            '9T Pro',
            '9T',
            'K20',
            'K20 Pro',
            'Note 7S',
            'Y3',
            '7',
            'Note 7 pro',
            'Mix 3',
            'Note 7',
            'Note 6 Pro',
            '8 pro',
            '8 Lite',
            'A2',
            'A2 Lite',
            '6',
            '6A',
            'Note 5 Pro',
            'Note 5',
            '5',
            '5A',
            'Y1',
            'Y1 Lite',
            'Note 3',
            'A1',
            '4',
            'Note 4',
            '4A',
            '4 Prime',
            '3s Prime',
            '3s',
            '3 Pro',
            '4s',
            '5',
            '3',
            '4i',
            'Other'
        ],
        Samsung:[
            'Galaxy A04s',
            'Galaxy A04',
            'Galaxy A23',
            'Galaxy M13',
            'Galaxy A13',
            'Galaxy F13',
            'Galaxy S20 FE',
            'Galaxy A53',
            'Galaxy A73',
            'Galaxy A33',
            'Galaxy F23',
            'Galaxy M33',
            'Galaxy M23',
            'Galaxy S21 FE',
            'Galaxy S22 Ultra',
            'Galaxy A03',
            'Galaxy A03 Core',
            'Galaxy F42',
            'Galaxy M52',
            'Galaxy M22',
            'Galaxy M32',
            'Galaxy A03s',
            'Galaxy A52s',
            'Galaxy A12',
            'Galaxy M21',
            'Galaxy F22',
            'Galaxy A22',
            'Galaxy F52',
            'Galaxy M42',
            'Galaxy M12',
            'Galaxy F12',
            'Galaxy F02s',
            'Galaxy A72',
            'Galaxy A52',
            'Galaxy A32',
            'Galaxy M62',
            'Galaxy F62',
            'Galaxy S21 Ultra',
            'Galaxy S21+',
            'Galaxy S21',
            'Galaxy M02s',
            'Galaxy M02',
            'Galaxy A02',
            'Galaxy A02s',
            'Galaxy M21s',
            'Galaxy M31 Prime',
            'Galaxy F41',
            'Galaxy S20 FE',
            'Galaxy A42',
            'Galaxy M51',
            'Galaxy A51',
            'Galaxy M31s',
            'Galaxy M01s',
            'Galaxy M01 Core',
            'Galaxy A01 Core',
            'Galaxy A71',
            'Galaxy M01',
            'Galaxy A21s',
            'Galaxy J2 Core',
            'Galaxy A71',
            'Galaxy A51',
            'Galaxy A21',
            'Galaxy M11',
            'Galaxy A31',
            'Galaxy A41',
            'Galaxy M21',
            'Galaxy A11',
            'Galaxy M31',
            'Galaxy S20 Ultra',
            'Galaxy S20+',
            'Galaxy S20',
            'Galaxy Note10 Lite',
            'Galaxy S10 Lite',
            'Galaxy A01',
            'Galaxy A70s',
            'Galaxy A20s',
            'Galaxy M30s',
            'Galaxy M10s',
            'Galaxy A90',
            'Galaxy A30s',
            'Galaxy A50s',
            'Galaxy Note10+',
            'Galaxy Note10',
            'Galaxy A10s',
            'Galaxy A2 Core',
            'Galaxy S10+',
            'Galaxy S10',
            'Galaxy M40',
            'Galaxy M30',
            'Galaxy M20',
            'Galaxy M10',
            'Galaxy A80',
            'Galaxy A70',
            'Galaxy A60',
            'Galaxy A50',
            'Galaxy A40',
            'Galaxy A30',
            'Galaxy A20',
            'Galaxy A10',
            'Galaxy A6s',
            'Galaxy A8s',
            'Galaxy A9',
            'Galaxy A7',
            'Galaxy Note9',
            'Galaxy J6+',
            'Galaxy J4 Core',
            'Galaxy J4+',
            'Galaxy J2 Core',
            'Galaxy On6',
            'Galaxy J7',
            'Galaxy J3',
            'Galaxy A8 Star',
            'Galaxy J8',
            'Galaxy J6',
            'Galaxy J4',
            'Galaxy A6+',
            'Galaxy A6',
            'Galaxy J7 Duo',
            'Galaxy J7 Prime',
            'Galaxy S9+',
            'Galaxy S9',
            'Galaxy J2 Pro',
            'Galaxy A8+',
            'Galaxy A8',
            'Galaxy J2',
            'Galaxy C7',
            'Galaxy Note8',
            'Galaxy S8 Active',
            'Galaxy J7 Max',
            'Galaxy J7',
            'Galaxy J7 Pro',
            'Galaxy J5',
            'Galaxy J3',
            'Galaxy S8',
            'GAlaxy S8+',
            'Galaxy C5 Pro',
            'Galaxy A7',
            'Galaxy A5',
            'Galaxy A3',
            'Galaxy J2 Prime',
            'Galaxy C10',
            'Galaxy C9 Pro',
            'Galaxy A8',
            'Galaxy On8',
            'Galaxy on7',
            'Galaxy J5 Prime',
            'Galaxy J7 Prime',
            'Other'
        ],
        Sony:[
            'Xperia 5 IV',
            'Xperia 1 IV',
            'Xperia 10 IV',
            'Xperia Pro-I',
            'Xperia 10 III Lite',
            'Xperia 1 III',
            'Xperia 5 III',
            'Xperia 10 III',
            'Xperia Pro',
            'Xperia 5 II',
            'Xperia 1 II',
            'Xperia 10 II',
            'Xperia L4',
            'Xperia 5',
            'Xperia 1',
            'Xperia 10 Plus',
            'Xperia 10',
            'Xperia L3',
            'Xperia XA2 Plus',
            'Xperia XZ3',
            'Xperia XZ2',
            'Xperia XZ2 Compact',
            'Xperia XA2 Ultra',
            'Xperia L2',
            'Xperia R1 Plus',
            'Xperia XA1 Plus',
            'Xperia XZ1'
        ],
        Vivo:[
            'Y73t',
            'X Fold+',
            'Y52t',
            'Y16',
            'Y75s',
            'Y22',
            'Y22s',
            'V25 Pro',
            'V25',
            'Y35',
            'Y02s',
            'Y30',
            'Y77',
            'Y72t',
            'T2',
            'Y75',
            'S15 Pro',
            'S15',
            'Y55',
            'X80 Pro',
            'X80',
            'T1',
            'T1X',
            'S15e',
            'X Note',
            'Y21G',
            'Y01',
            'Y33s',
            'Y33',
            'Y55',
            'V23 Pro',
            'V23',
            'Y33t',
            'Y21t',
            'Y21a',
            'Y21e',
            'S12 Pro',
            'S12',
            'Y32',
            'Y55s',
            'V23e',
            'Y76',
            'Y54s',
            'Y50t',
            'Y15a',
            'Y74s',
            'Y76s',
            'Y15s',
            'Y71t',
            'T1X',
            'T1',
            'Y3s',
            'Y20t',
            'Y21s',
            'X80 Pro+',
            'X70 Pro+',
            'X70 Pro',
            'X70',
            'Y33s',
            'Y21',
            'Y12a',
            'S10 pro',
            'S10',
            'Y73',
            'Y72',
            'Y53s',
            'Y70t',
            'Y12s',
            'V21',
            'V21e',
            'Y20s',
            'Y30g',
            'X60 Pro',
            'X60',
            'Y72',
            'S9',
            'S9e',
            'S7t',
            'Y31',
            'Y20g',
            'Y31s',
            'Y20a',
            'Y20',
            'V20',
            'Y52s',
            'Y51a',
            'Y51',
            'Y12s',
            'Y12i',
            'Y1s',
            'S7e',
            'Y3s',
            'Y30',
            'Y11s',
            'Y70',
            'Y20s',
            'Y73s',
            'V20',
            'V20 SE',
            'V20 Pro',
            'Y20i',
            'Y20',
            'S7',
            'Y51s',
            'Y70s',
            'Y30',
            'Y50',
            'V19',
            'X30',
            'V17',
            'Y9s',
            'V17',
            'Y5s',
            'Y19',
            'Y11',
            'Y3',
            'V17 Pro',
            'Y17',
            'Y15',
            'Y12',
            'V15',
            'V15 Pro',
            'Y89',
            'Y93',
            'Y93s',
            'Y95',
            'Y91i',
            'Y93',
            'Y91i',
            'Y91',
            'V11i',
            'Y97',
            'Y81',
            'V9',
            'V7',
            'Other'
        ]
    }
}